### ISSUE TITLE
AttributeError: 'module' object has no attribute 'commit_on_success'

### ISSUE THREAD

**Issue by shivakrshn49** [mjr27/django-flatpages-tinymce#12]
After upgrading django to 1.8 the below error was facing when running django development server

Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/username/.virtualenvs/project/lib/python2.7/site-packages/django/core/management/**init**.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/username/.virtualenvs/project/lib/python2.7/site-packages/django/core/management/**init**.py", line 312, in execute
    django.setup()
  File "/Users/username/.virtualenvs/project/lib/python2.7/site-packages/django/**init**.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/username/.virtualenvs/project/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/Users/username/.virtualenvs/project/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/Users/username/.virtualenvs/project/lib/python2.7/site-packages/django/contrib/admin/**init**.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/username/.virtualenvs/project/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/Users/username/.virtualenvs/project/lib/python2.7/site-packages/flatpages_tinymce/admin.py", line 16, in <module>
    class FlatPageAdmin(flatpages_admin.FlatPageAdmin):
  File "/Users/username/.virtualenvs/project/lib/python2.7/site-packages/flatpages_tinymce/admin.py", line 22, in FlatPageAdmin
    @transaction.commit_on_success
AttributeError: 'module' object has no attribute 'commit_on_success'

I think  the app needs to be updated according to django 1.8
